# Docker Compose file for testing
version: "2"
services:

  db_test:
    build:
      context: ./pg_custom/
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: critiquebrainz
      POSTGRES_PASSWORD: critiquebrainz
      POSTGRES_DB: critiquebrainz
    network_mode: bridge

  critiquebrainz_redis:
    image: redis:3.2.1
    network_mode: bridge

  critiquebrainz_test:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.test
    links:
      - db_test
      - critiquebrainz_redis
    network_mode: bridge
