# Docker Compose file for development
version: "2"
services:

  db:
    extends:
      file: ./common.yml
      service: db
    volumes:
      - ../data/pgdata:/var/lib/postgresql/data/pgdata
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata

  critiquebrainz:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - ../:/code
      - ../data/app:/data
    ports:
      - "80:80"
    depends_on:
      - db
      - critiquebrainz-redis

  critiquebrainz-redis:
    image: redis:3.2.1
